"""jsrun launcher support"""

from e4s_cl.cf.launchers import Parser

SCRIPT_NAMES = ['jsrun']

ARGUMENTS = {
    "--allocate_only": 1,
    "--appfile": 1,
    "--bind": 1,
    "--chdir": 1,
    "--cpu_per_rs": 1,
    "--env": 1,
    "--env_eval": 1,
    "--env_no_propagate": 1,
    "--erf_input": 1,
    "--erf_output": 1,
    "--erf_output_pidx": 1,
    "--exclude_hosts": 1,
    "--exit_on_error": 1,
    "--gpu_per_rs": 1,
    "--help": 0,
    "--immediate": 0,
    "--latency_priority": 1,
    "--launch_distribution": 1,
    "--launch_node_task": 1,
    "--memory_per_rs": 1,
    "--np": 1,
    "--nrs": 1,
    "--pre_post_exec": 1,
    "--print_placement": 1,
    "--progress": 1,
    "--rs_per_host": 1,
    "--rs_per_socket": 1,
    "--save_resources": 1,
    "--smpiargs": 1,
    "--stdin_rank": 1,
    "--stdio_input": 1,
    "--stdio_mode": 1,
    "--stdio_stderr": 1,
    "--stdio_stdout": 1,
    "--tasks_per_rs": 1,
    "--usage": 0,
    "--use_reservation": 1,
    "--use_resources": 1,
    "--use_spindle": 1,
    "--version": 0,
    "-?": 0,
    "-A": 1,
    "-D": 1,
    "-E": 1,
    "-F": 1,
    "-H": 1,
    "-I": 1,
    "-J": 1,
    "-K": 1,
    "-L": 1,
    "-M": 1,
    "-P": 1,
    "-S": 1,
    "-U": 1,
    "-V": 0,
    "-X": 1,
    "-Z": 1,
    "-a": 1,
    "-b": 1,
    "-c": 1,
    "-d": 1,
    "-e": 1,
    "-f": 1,
    "-g": 1,
    "-h": 1,
    "-i": 0,
    "-k": 1,
    "-l": 1,
    "-m": 1,
    "-n": 1,
    "-o": 1,
    "-p": 1,
    "-r": 1,
    "-t": 1,
    "-x": 1,
}

PARSER = Parser(ARGUMENTS)
