#!/bin/env python3

import sys

from e4s_cl.cli.commands.__main__ import COMMAND as cli_main_cmd

if __name__ == '__main__':

    if getattr(sys, 'frozen', False):
        __file__ = sys.executable

    sys.exit(cli_main_cmd.main(sys.argv[1:]))
