#!/bin/env python3

if __name__ == '__main__':
    import os
    import sys
    from contextlib import contextmanager

    if getattr(sys, 'frozen', False):
        __file__ = sys.executable

    here = os.path.realpath(os.path.dirname(__file__))
    os.environ['__E4S_CL_HOME__'] = os.path.join(here, '..')
    packages = os.path.join(here, '..', 'packages')
    sys.path.insert(0, packages)

    from e4s_cl.cli.commands.__main__ import COMMAND as cli_main_cmd
    sys.exit(cli_main_cmd.main(sys.argv[1:]))

