#!/bin/env python3

import os
import sys
from contextlib import contextmanager
from pathlib import Path

from e4s_cl.cli.commands.__main__ import COMMAND as cli_main_cmd


def e4s_cl_home(candidates):
    """
    candidates: list[Path]
    If the script has been relocated due to a scheduler (ALPS), try to find
    the install directory from paths of interest
    """
    for path in candidates:
        if Path(path, 'packages', 'e4s_cl').exists():
            return path

    print("The e4s_cl package could not be found.", file=sys.stderr)
    sys.exit(1)


if __name__ == '__main__':

    if getattr(sys, 'frozen', False):
        __file__ = sys.executable

    # Look for the home in the parent of the script, then the parent of the interpreter
    #candidates = [Path(__file__).parents[1], Path(sys.executable).parents[2]]

    #install_dir = e4s_cl_home(candidates)
    #os.environ['__E4S_CL_HOME__'] = install_dir.as_posix()

    sys.exit(cli_main_cmd.main(sys.argv[1:]))
