# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: Run Setup script and tests

on: [ push, pull_request ]

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run setup
      run: make && make install

  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test with tox
      run: |
        make test
